name: OTRP build Windows 32bit

on:
  push:
    tags:
      - v*

jobs:
  wingdi32:
    runs-on: windows-latest
    steps:

      - name: Setup Mingw
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: git zip unzip svn base-devel mingw-w64-i686-toolchain autoconf mingw-w64-i686-gcc mingw-w64-i686-freetype mingw-w64-i686-zstd mingw-w64-i686-libpng mingw-w64-i686-brotli mingw-w64-i686-pkg-config

      - name: Checkout code
        uses: actions/checkout@v2

      - name: CI-Build
        run: sh ./.github/build32.sh
        shell: msys2 {0}

      - name: Upload sim.exe
        uses: actions/upload-artifact@v2
        with:
          name: sim-WinGDI-OTRP.exe
          path: ./sim-WinGDI-OTRP.exe
